package com.example.booker.register;

public enum RegisterError {
    EMPTY_EMAIL,
    EMPTY_PASSWORD,
    EMPTY_LASTNAME,
    EMPTY_FIRSTNAME,
    EMPTY_PHONE,
    INVALID_EMAIL,
    INVALID_PHONE,
    EMAIL_ALREADY_EXIST,
    PASSWORD_CONFIRMATION_EMPTY,
    PASSWORD_CONFIRMATION_FAILED,
    UNKNOWN
}
